server:
  port: 9527

spring:
  application:
    name: gateway_module
  cloud:
    consul:
      host: localhost
      port: 8500

logging:
  level:
    org.springframework.cloud: DEBUG

zuul:
  prefix: /records
  ignored-services: "*"
  routes:
    records:
      path: /**
      service-id: records-module
